---
abstract: 'Add U.S. states to CGI::Untaint::CountyStateProvince tables'
author:
  - 'Nigel Horne <njh@bandsman.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Untaint-CountyStateProvince-US
no_index:
  directory:
    - t
    - inc
requires:
  CGI::Untaint: 0
  CGI::Untaint::CountyStateProvince: 0.04
  Locale::SubCountry: 0
  Test::Kwalitee: 0
  Test::More: 0.82
  Test::NoWarnings: 0
version: 0.02
